In [1]:
import torch
import torch.nn as nn

In [ ]:
nn.Conv2d()

In [6]:
image = torch.rand((3, 9,9))
image

tensor([[[5.9773e-01, 3.8772e-01, 5.3190e-01, 9.9946e-01, 4.6761e-01,
          4.1240e-01, 8.5366e-01, 1.2489e-01, 6.5401e-01],
         [4.0953e-01, 9.2767e-01, 2.5992e-01, 8.3491e-01, 3.4729e-01,
          1.4718e-01, 2.8361e-01, 5.2382e-01, 2.3179e-02],
         [9.7710e-01, 4.9774e-01, 7.8089e-01, 4.6496e-01, 3.4258e-01,
          2.2089e-01, 8.2030e-01, 9.0873e-01, 5.6245e-01],
         [3.7015e-01, 5.3635e-01, 1.6028e-01, 1.5529e-01, 7.5457e-01,
          4.8041e-01, 8.9244e-01, 2.1568e-01, 9.7410e-01],
         [3.4980e-01, 9.7773e-01, 4.7684e-01, 4.6388e-01, 6.3878e-01,
          3.2054e-01, 5.6122e-01, 3.0600e-01, 8.6292e-01],
         [3.6644e-02, 3.4645e-01, 2.9805e-01, 1.8591e-01, 1.8580e-01,
          7.3524e-01, 2.6592e-01, 4.6310e-01, 5.5753e-01],
         [6.7517e-01, 7.5810e-01, 8.0956e-01, 2.0128e-01, 8.8264e-01,
          3.4543e-02, 4.7220e-02, 4.6464e-01, 4.1601e-01],
         [2.5235e-01, 9.5804e-01, 2.0107e-01, 6.2737e-01, 5.6492e-01,
          8.0859e-01, 5.782

In [12]:
conv1 = nn.Conv2d(3, 5, 3, stride = 2)

In [13]:
conv1(image).shape

torch.Size([5, 4, 4])

In [14]:
conv = nn.Conv2d(3,5,3)

In [ ]:
conv(image).shape

torch.Size([5, 7, 7])

In [17]:
pool1 = nn.MaxPool2d(3)

In [18]:
pool1(image)

tensor([[[0.9771, 0.9995, 0.9087],
         [0.9777, 0.7546, 0.9741],
         [0.9580, 0.9991, 0.8883]],

        [[0.7470, 0.9426, 0.9206],
         [0.9700, 0.9968, 0.9788],
         [0.7786, 0.8502, 0.8142]],

        [[0.8881, 0.8768, 0.7734],
         [0.7786, 0.8403, 0.9073],
         [0.7787, 0.9685, 0.9968]]])

In [36]:
# RGB images 32x32
model = nn.Sequential(
    nn.Conv2d(3, 6, 3, padding = 1),
    nn.ReLU(),
    nn.Conv2d(6, 6, 3, padding = 1),
    nn.ReLU(),
    nn.MaxPool2d(2), # 6x16x16
    nn.Conv2d(6, 12, 3, padding = 1),
    nn.ReLU(),
    nn.Conv2d(12, 12, 3, padding = 1),
    nn.Flatten(0, -1), #12*16x16
    nn.Linear(12*16*16, 128),
    nn.ReLU(),
    nn.Linear(128, 10), # 10 classes
)

In [37]:
params = list(model.parameters())

In [38]:
sumparam = sum(p.numel() for p in params)
sumparam

397100

In [39]:
img = torch.randn((3, 32, 32))

In [40]:
model(img)

tensor([-0.0819, -0.0107,  0.0082,  0.0303,  0.0277,  0.0192, -0.0398,  0.0287,
         0.0083, -0.0233], grad_fn=<ViewBackward0>)